// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RemoteCall.proto

package zh.lisa;

public final class RemoteCallProtocolProto {
  private RemoteCallProtocolProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RemoteCallProtocolOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string serviceName = 1;
    /**
     * <code>required string serviceName = 1;</code>
     */
    boolean hasServiceName();
    /**
     * <code>required string serviceName = 1;</code>
     */
    java.lang.String getServiceName();
    /**
     * <code>required string serviceName = 1;</code>
     */
    com.google.protobuf.ByteString
        getServiceNameBytes();

    // required string methodName = 2;
    /**
     * <code>required string methodName = 2;</code>
     */
    boolean hasMethodName();
    /**
     * <code>required string methodName = 2;</code>
     */
    java.lang.String getMethodName();
    /**
     * <code>required string methodName = 2;</code>
     */
    com.google.protobuf.ByteString
        getMethodNameBytes();

    // optional bytes paramByte = 3;
    /**
     * <code>optional bytes paramByte = 3;</code>
     */
    boolean hasParamByte();
    /**
     * <code>optional bytes paramByte = 3;</code>
     */
    com.google.protobuf.ByteString getParamByte();

    // repeated string paramType = 4;
    /**
     * <code>repeated string paramType = 4;</code>
     */
    java.util.List<java.lang.String>
    getParamTypeList();
    /**
     * <code>repeated string paramType = 4;</code>
     */
    int getParamTypeCount();
    /**
     * <code>repeated string paramType = 4;</code>
     */
    java.lang.String getParamType(int index);
    /**
     * <code>repeated string paramType = 4;</code>
     */
    com.google.protobuf.ByteString
        getParamTypeBytes(int index);

    // repeated string listParamType = 5;
    /**
     * <code>repeated string listParamType = 5;</code>
     */
    java.util.List<java.lang.String>
    getListParamTypeList();
    /**
     * <code>repeated string listParamType = 5;</code>
     */
    int getListParamTypeCount();
    /**
     * <code>repeated string listParamType = 5;</code>
     */
    java.lang.String getListParamType(int index);
    /**
     * <code>repeated string listParamType = 5;</code>
     */
    com.google.protobuf.ByteString
        getListParamTypeBytes(int index);

    // repeated int32 paramByteLength = 6;
    /**
     * <code>repeated int32 paramByteLength = 6;</code>
     */
    java.util.List<java.lang.Integer> getParamByteLengthList();
    /**
     * <code>repeated int32 paramByteLength = 6;</code>
     */
    int getParamByteLengthCount();
    /**
     * <code>repeated int32 paramByteLength = 6;</code>
     */
    int getParamByteLength(int index);
  }
  /**
   * Protobuf type {@code RemoteCallProtocol}
   */
  public static final class RemoteCallProtocol extends
      com.google.protobuf.GeneratedMessage
      implements RemoteCallProtocolOrBuilder {
    // Use RemoteCallProtocol.newBuilder() to construct.
    private RemoteCallProtocol(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RemoteCallProtocol(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RemoteCallProtocol defaultInstance;
    public static RemoteCallProtocol getDefaultInstance() {
      return defaultInstance;
    }

    public RemoteCallProtocol getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RemoteCallProtocol(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              serviceName_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              methodName_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              paramByte_ = input.readBytes();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                paramType_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              paramType_.add(input.readBytes());
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                listParamType_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              listParamType_.add(input.readBytes());
              break;
            }
            case 48: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                paramByteLength_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000020;
              }
              paramByteLength_.add(input.readInt32());
              break;
            }
            case 50: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020) && input.getBytesUntilLimit() > 0) {
                paramByteLength_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000020;
              }
              while (input.getBytesUntilLimit() > 0) {
                paramByteLength_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          paramType_ = new com.google.protobuf.UnmodifiableLazyStringList(paramType_);
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          listParamType_ = new com.google.protobuf.UnmodifiableLazyStringList(listParamType_);
        }
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          paramByteLength_ = java.util.Collections.unmodifiableList(paramByteLength_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return zh.lisa.RemoteCallProtocolProto.internal_static_RemoteCallProtocol_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return zh.lisa.RemoteCallProtocolProto.internal_static_RemoteCallProtocol_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              zh.lisa.RemoteCallProtocolProto.RemoteCallProtocol.class, zh.lisa.RemoteCallProtocolProto.RemoteCallProtocol.Builder.class);
    }

    public static com.google.protobuf.Parser<RemoteCallProtocol> PARSER =
        new com.google.protobuf.AbstractParser<RemoteCallProtocol>() {
      public RemoteCallProtocol parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RemoteCallProtocol(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RemoteCallProtocol> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string serviceName = 1;
    public static final int SERVICENAME_FIELD_NUMBER = 1;
    private java.lang.Object serviceName_;
    /**
     * <code>required string serviceName = 1;</code>
     */
    public boolean hasServiceName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string serviceName = 1;</code>
     */
    public java.lang.String getServiceName() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serviceName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string serviceName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getServiceNameBytes() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string methodName = 2;
    public static final int METHODNAME_FIELD_NUMBER = 2;
    private java.lang.Object methodName_;
    /**
     * <code>required string methodName = 2;</code>
     */
    public boolean hasMethodName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string methodName = 2;</code>
     */
    public java.lang.String getMethodName() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          methodName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string methodName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMethodNameBytes() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        methodName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bytes paramByte = 3;
    public static final int PARAMBYTE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString paramByte_;
    /**
     * <code>optional bytes paramByte = 3;</code>
     */
    public boolean hasParamByte() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes paramByte = 3;</code>
     */
    public com.google.protobuf.ByteString getParamByte() {
      return paramByte_;
    }

    // repeated string paramType = 4;
    public static final int PARAMTYPE_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList paramType_;
    /**
     * <code>repeated string paramType = 4;</code>
     */
    public java.util.List<java.lang.String>
        getParamTypeList() {
      return paramType_;
    }
    /**
     * <code>repeated string paramType = 4;</code>
     */
    public int getParamTypeCount() {
      return paramType_.size();
    }
    /**
     * <code>repeated string paramType = 4;</code>
     */
    public java.lang.String getParamType(int index) {
      return paramType_.get(index);
    }
    /**
     * <code>repeated string paramType = 4;</code>
     */
    public com.google.protobuf.ByteString
        getParamTypeBytes(int index) {
      return paramType_.getByteString(index);
    }

    // repeated string listParamType = 5;
    public static final int LISTPARAMTYPE_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList listParamType_;
    /**
     * <code>repeated string listParamType = 5;</code>
     */
    public java.util.List<java.lang.String>
        getListParamTypeList() {
      return listParamType_;
    }
    /**
     * <code>repeated string listParamType = 5;</code>
     */
    public int getListParamTypeCount() {
      return listParamType_.size();
    }
    /**
     * <code>repeated string listParamType = 5;</code>
     */
    public java.lang.String getListParamType(int index) {
      return listParamType_.get(index);
    }
    /**
     * <code>repeated string listParamType = 5;</code>
     */
    public com.google.protobuf.ByteString
        getListParamTypeBytes(int index) {
      return listParamType_.getByteString(index);
    }

    // repeated int32 paramByteLength = 6;
    public static final int PARAMBYTELENGTH_FIELD_NUMBER = 6;
    private java.util.List<java.lang.Integer> paramByteLength_;
    /**
     * <code>repeated int32 paramByteLength = 6;</code>
     */
    public java.util.List<java.lang.Integer>
        getParamByteLengthList() {
      return paramByteLength_;
    }
    /**
     * <code>repeated int32 paramByteLength = 6;</code>
     */
    public int getParamByteLengthCount() {
      return paramByteLength_.size();
    }
    /**
     * <code>repeated int32 paramByteLength = 6;</code>
     */
    public int getParamByteLength(int index) {
      return paramByteLength_.get(index);
    }

    private void initFields() {
      serviceName_ = "";
      methodName_ = "";
      paramByte_ = com.google.protobuf.ByteString.EMPTY;
      paramType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      listParamType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      paramByteLength_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasServiceName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMethodName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getServiceNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMethodNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, paramByte_);
      }
      for (int i = 0; i < paramType_.size(); i++) {
        output.writeBytes(4, paramType_.getByteString(i));
      }
      for (int i = 0; i < listParamType_.size(); i++) {
        output.writeBytes(5, listParamType_.getByteString(i));
      }
      for (int i = 0; i < paramByteLength_.size(); i++) {
        output.writeInt32(6, paramByteLength_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getServiceNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMethodNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, paramByte_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < paramType_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(paramType_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getParamTypeList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < listParamType_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(listParamType_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getListParamTypeList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < paramByteLength_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(paramByteLength_.get(i));
        }
        size += dataSize;
        size += 1 * getParamByteLengthList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static zh.lisa.RemoteCallProtocolProto.RemoteCallProtocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zh.lisa.RemoteCallProtocolProto.RemoteCallProtocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zh.lisa.RemoteCallProtocolProto.RemoteCallProtocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zh.lisa.RemoteCallProtocolProto.RemoteCallProtocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zh.lisa.RemoteCallProtocolProto.RemoteCallProtocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static zh.lisa.RemoteCallProtocolProto.RemoteCallProtocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static zh.lisa.RemoteCallProtocolProto.RemoteCallProtocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static zh.lisa.RemoteCallProtocolProto.RemoteCallProtocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static zh.lisa.RemoteCallProtocolProto.RemoteCallProtocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static zh.lisa.RemoteCallProtocolProto.RemoteCallProtocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(zh.lisa.RemoteCallProtocolProto.RemoteCallProtocol prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RemoteCallProtocol}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements zh.lisa.RemoteCallProtocolProto.RemoteCallProtocolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return zh.lisa.RemoteCallProtocolProto.internal_static_RemoteCallProtocol_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return zh.lisa.RemoteCallProtocolProto.internal_static_RemoteCallProtocol_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                zh.lisa.RemoteCallProtocolProto.RemoteCallProtocol.class, zh.lisa.RemoteCallProtocolProto.RemoteCallProtocol.Builder.class);
      }

      // Construct using zh.lisa.RemoteCallProtocolProto.RemoteCallProtocol.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        serviceName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        methodName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        paramByte_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        paramType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        listParamType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        paramByteLength_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return zh.lisa.RemoteCallProtocolProto.internal_static_RemoteCallProtocol_descriptor;
      }

      public zh.lisa.RemoteCallProtocolProto.RemoteCallProtocol getDefaultInstanceForType() {
        return zh.lisa.RemoteCallProtocolProto.RemoteCallProtocol.getDefaultInstance();
      }

      public zh.lisa.RemoteCallProtocolProto.RemoteCallProtocol build() {
        zh.lisa.RemoteCallProtocolProto.RemoteCallProtocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public zh.lisa.RemoteCallProtocolProto.RemoteCallProtocol buildPartial() {
        zh.lisa.RemoteCallProtocolProto.RemoteCallProtocol result = new zh.lisa.RemoteCallProtocolProto.RemoteCallProtocol(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serviceName_ = serviceName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.methodName_ = methodName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.paramByte_ = paramByte_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          paramType_ = new com.google.protobuf.UnmodifiableLazyStringList(
              paramType_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.paramType_ = paramType_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          listParamType_ = new com.google.protobuf.UnmodifiableLazyStringList(
              listParamType_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.listParamType_ = listParamType_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          paramByteLength_ = java.util.Collections.unmodifiableList(paramByteLength_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.paramByteLength_ = paramByteLength_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof zh.lisa.RemoteCallProtocolProto.RemoteCallProtocol) {
          return mergeFrom((zh.lisa.RemoteCallProtocolProto.RemoteCallProtocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(zh.lisa.RemoteCallProtocolProto.RemoteCallProtocol other) {
        if (other == zh.lisa.RemoteCallProtocolProto.RemoteCallProtocol.getDefaultInstance()) return this;
        if (other.hasServiceName()) {
          bitField0_ |= 0x00000001;
          serviceName_ = other.serviceName_;
          onChanged();
        }
        if (other.hasMethodName()) {
          bitField0_ |= 0x00000002;
          methodName_ = other.methodName_;
          onChanged();
        }
        if (other.hasParamByte()) {
          setParamByte(other.getParamByte());
        }
        if (!other.paramType_.isEmpty()) {
          if (paramType_.isEmpty()) {
            paramType_ = other.paramType_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureParamTypeIsMutable();
            paramType_.addAll(other.paramType_);
          }
          onChanged();
        }
        if (!other.listParamType_.isEmpty()) {
          if (listParamType_.isEmpty()) {
            listParamType_ = other.listParamType_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureListParamTypeIsMutable();
            listParamType_.addAll(other.listParamType_);
          }
          onChanged();
        }
        if (!other.paramByteLength_.isEmpty()) {
          if (paramByteLength_.isEmpty()) {
            paramByteLength_ = other.paramByteLength_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureParamByteLengthIsMutable();
            paramByteLength_.addAll(other.paramByteLength_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasServiceName()) {
          
          return false;
        }
        if (!hasMethodName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        zh.lisa.RemoteCallProtocolProto.RemoteCallProtocol parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (zh.lisa.RemoteCallProtocolProto.RemoteCallProtocol) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string serviceName = 1;
      private java.lang.Object serviceName_ = "";
      /**
       * <code>required string serviceName = 1;</code>
       */
      public boolean hasServiceName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string serviceName = 1;</code>
       */
      public java.lang.String getServiceName() {
        java.lang.Object ref = serviceName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          serviceName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string serviceName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getServiceNameBytes() {
        java.lang.Object ref = serviceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serviceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string serviceName = 1;</code>
       */
      public Builder setServiceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serviceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string serviceName = 1;</code>
       */
      public Builder clearServiceName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serviceName_ = getDefaultInstance().getServiceName();
        onChanged();
        return this;
      }
      /**
       * <code>required string serviceName = 1;</code>
       */
      public Builder setServiceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serviceName_ = value;
        onChanged();
        return this;
      }

      // required string methodName = 2;
      private java.lang.Object methodName_ = "";
      /**
       * <code>required string methodName = 2;</code>
       */
      public boolean hasMethodName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string methodName = 2;</code>
       */
      public java.lang.String getMethodName() {
        java.lang.Object ref = methodName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          methodName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string methodName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMethodNameBytes() {
        java.lang.Object ref = methodName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          methodName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string methodName = 2;</code>
       */
      public Builder setMethodName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        methodName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string methodName = 2;</code>
       */
      public Builder clearMethodName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        methodName_ = getDefaultInstance().getMethodName();
        onChanged();
        return this;
      }
      /**
       * <code>required string methodName = 2;</code>
       */
      public Builder setMethodNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        methodName_ = value;
        onChanged();
        return this;
      }

      // optional bytes paramByte = 3;
      private com.google.protobuf.ByteString paramByte_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes paramByte = 3;</code>
       */
      public boolean hasParamByte() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes paramByte = 3;</code>
       */
      public com.google.protobuf.ByteString getParamByte() {
        return paramByte_;
      }
      /**
       * <code>optional bytes paramByte = 3;</code>
       */
      public Builder setParamByte(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        paramByte_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes paramByte = 3;</code>
       */
      public Builder clearParamByte() {
        bitField0_ = (bitField0_ & ~0x00000004);
        paramByte_ = getDefaultInstance().getParamByte();
        onChanged();
        return this;
      }

      // repeated string paramType = 4;
      private com.google.protobuf.LazyStringList paramType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureParamTypeIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          paramType_ = new com.google.protobuf.LazyStringArrayList(paramType_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string paramType = 4;</code>
       */
      public java.util.List<java.lang.String>
          getParamTypeList() {
        return java.util.Collections.unmodifiableList(paramType_);
      }
      /**
       * <code>repeated string paramType = 4;</code>
       */
      public int getParamTypeCount() {
        return paramType_.size();
      }
      /**
       * <code>repeated string paramType = 4;</code>
       */
      public java.lang.String getParamType(int index) {
        return paramType_.get(index);
      }
      /**
       * <code>repeated string paramType = 4;</code>
       */
      public com.google.protobuf.ByteString
          getParamTypeBytes(int index) {
        return paramType_.getByteString(index);
      }
      /**
       * <code>repeated string paramType = 4;</code>
       */
      public Builder setParamType(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParamTypeIsMutable();
        paramType_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string paramType = 4;</code>
       */
      public Builder addParamType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParamTypeIsMutable();
        paramType_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string paramType = 4;</code>
       */
      public Builder addAllParamType(
          java.lang.Iterable<java.lang.String> values) {
        ensureParamTypeIsMutable();
        super.addAll(values, paramType_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string paramType = 4;</code>
       */
      public Builder clearParamType() {
        paramType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string paramType = 4;</code>
       */
      public Builder addParamTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParamTypeIsMutable();
        paramType_.add(value);
        onChanged();
        return this;
      }

      // repeated string listParamType = 5;
      private com.google.protobuf.LazyStringList listParamType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureListParamTypeIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          listParamType_ = new com.google.protobuf.LazyStringArrayList(listParamType_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated string listParamType = 5;</code>
       */
      public java.util.List<java.lang.String>
          getListParamTypeList() {
        return java.util.Collections.unmodifiableList(listParamType_);
      }
      /**
       * <code>repeated string listParamType = 5;</code>
       */
      public int getListParamTypeCount() {
        return listParamType_.size();
      }
      /**
       * <code>repeated string listParamType = 5;</code>
       */
      public java.lang.String getListParamType(int index) {
        return listParamType_.get(index);
      }
      /**
       * <code>repeated string listParamType = 5;</code>
       */
      public com.google.protobuf.ByteString
          getListParamTypeBytes(int index) {
        return listParamType_.getByteString(index);
      }
      /**
       * <code>repeated string listParamType = 5;</code>
       */
      public Builder setListParamType(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureListParamTypeIsMutable();
        listParamType_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string listParamType = 5;</code>
       */
      public Builder addListParamType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureListParamTypeIsMutable();
        listParamType_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string listParamType = 5;</code>
       */
      public Builder addAllListParamType(
          java.lang.Iterable<java.lang.String> values) {
        ensureListParamTypeIsMutable();
        super.addAll(values, listParamType_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string listParamType = 5;</code>
       */
      public Builder clearListParamType() {
        listParamType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string listParamType = 5;</code>
       */
      public Builder addListParamTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureListParamTypeIsMutable();
        listParamType_.add(value);
        onChanged();
        return this;
      }

      // repeated int32 paramByteLength = 6;
      private java.util.List<java.lang.Integer> paramByteLength_ = java.util.Collections.emptyList();
      private void ensureParamByteLengthIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          paramByteLength_ = new java.util.ArrayList<java.lang.Integer>(paramByteLength_);
          bitField0_ |= 0x00000020;
         }
      }
      /**
       * <code>repeated int32 paramByteLength = 6;</code>
       */
      public java.util.List<java.lang.Integer>
          getParamByteLengthList() {
        return java.util.Collections.unmodifiableList(paramByteLength_);
      }
      /**
       * <code>repeated int32 paramByteLength = 6;</code>
       */
      public int getParamByteLengthCount() {
        return paramByteLength_.size();
      }
      /**
       * <code>repeated int32 paramByteLength = 6;</code>
       */
      public int getParamByteLength(int index) {
        return paramByteLength_.get(index);
      }
      /**
       * <code>repeated int32 paramByteLength = 6;</code>
       */
      public Builder setParamByteLength(
          int index, int value) {
        ensureParamByteLengthIsMutable();
        paramByteLength_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 paramByteLength = 6;</code>
       */
      public Builder addParamByteLength(int value) {
        ensureParamByteLengthIsMutable();
        paramByteLength_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 paramByteLength = 6;</code>
       */
      public Builder addAllParamByteLength(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureParamByteLengthIsMutable();
        super.addAll(values, paramByteLength_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 paramByteLength = 6;</code>
       */
      public Builder clearParamByteLength() {
        paramByteLength_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:RemoteCallProtocol)
    }

    static {
      defaultInstance = new RemoteCallProtocol(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RemoteCallProtocol)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RemoteCallProtocol_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RemoteCallProtocol_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020RemoteCall.proto\"\223\001\n\022RemoteCallProtoco" +
      "l\022\023\n\013serviceName\030\001 \002(\t\022\022\n\nmethodName\030\002 \002" +
      "(\t\022\021\n\tparamByte\030\003 \001(\014\022\021\n\tparamType\030\004 \003(\t" +
      "\022\025\n\rlistParamType\030\005 \003(\t\022\027\n\017paramByteLeng" +
      "th\030\006 \003(\005B\"\n\007zh.lisaB\027RemoteCallProtocolP" +
      "roto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_RemoteCallProtocol_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_RemoteCallProtocol_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_RemoteCallProtocol_descriptor,
              new java.lang.String[] { "ServiceName", "MethodName", "ParamByte", "ParamType", "ListParamType", "ParamByteLength", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
