// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RemoteCallResult.proto

package zh.lisa;

public final class RemoteCallResultProto {
  private RemoteCallResultProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RemoteCallResultOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bool isSuccess = 1;
    /**
     * <code>required bool isSuccess = 1;</code>
     */
    boolean hasIsSuccess();
    /**
     * <code>required bool isSuccess = 1;</code>
     */
    boolean getIsSuccess();

    // optional bytes resultObj = 2;
    /**
     * <code>optional bytes resultObj = 2;</code>
     */
    boolean hasResultObj();
    /**
     * <code>optional bytes resultObj = 2;</code>
     */
    com.google.protobuf.ByteString getResultObj();

    // optional string resultType = 3;
    /**
     * <code>optional string resultType = 3;</code>
     */
    boolean hasResultType();
    /**
     * <code>optional string resultType = 3;</code>
     */
    java.lang.String getResultType();
    /**
     * <code>optional string resultType = 3;</code>
     */
    com.google.protobuf.ByteString
        getResultTypeBytes();

    // optional string errorMsg = 4;
    /**
     * <code>optional string errorMsg = 4;</code>
     */
    boolean hasErrorMsg();
    /**
     * <code>optional string errorMsg = 4;</code>
     */
    java.lang.String getErrorMsg();
    /**
     * <code>optional string errorMsg = 4;</code>
     */
    com.google.protobuf.ByteString
        getErrorMsgBytes();

    // optional int32 resultListSize = 5;
    /**
     * <code>optional int32 resultListSize = 5;</code>
     */
    boolean hasResultListSize();
    /**
     * <code>optional int32 resultListSize = 5;</code>
     */
    int getResultListSize();

    // optional string resultListType = 6;
    /**
     * <code>optional string resultListType = 6;</code>
     */
    boolean hasResultListType();
    /**
     * <code>optional string resultListType = 6;</code>
     */
    java.lang.String getResultListType();
    /**
     * <code>optional string resultListType = 6;</code>
     */
    com.google.protobuf.ByteString
        getResultListTypeBytes();

    // repeated int32 resultListObjLength = 7;
    /**
     * <code>repeated int32 resultListObjLength = 7;</code>
     */
    java.util.List<java.lang.Integer> getResultListObjLengthList();
    /**
     * <code>repeated int32 resultListObjLength = 7;</code>
     */
    int getResultListObjLengthCount();
    /**
     * <code>repeated int32 resultListObjLength = 7;</code>
     */
    int getResultListObjLength(int index);
  }
  /**
   * Protobuf type {@code RemoteCallResult}
   */
  public static final class RemoteCallResult extends
      com.google.protobuf.GeneratedMessage
      implements RemoteCallResultOrBuilder {
    // Use RemoteCallResult.newBuilder() to construct.
    private RemoteCallResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RemoteCallResult(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RemoteCallResult defaultInstance;
    public static RemoteCallResult getDefaultInstance() {
      return defaultInstance;
    }

    public RemoteCallResult getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RemoteCallResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              isSuccess_ = input.readBool();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              resultObj_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              resultType_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              errorMsg_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              resultListSize_ = input.readInt32();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              resultListType_ = input.readBytes();
              break;
            }
            case 56: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                resultListObjLength_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000040;
              }
              resultListObjLength_.add(input.readInt32());
              break;
            }
            case 58: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040) && input.getBytesUntilLimit() > 0) {
                resultListObjLength_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000040;
              }
              while (input.getBytesUntilLimit() > 0) {
                resultListObjLength_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          resultListObjLength_ = java.util.Collections.unmodifiableList(resultListObjLength_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return zh.lisa.RemoteCallResultProto.internal_static_RemoteCallResult_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return zh.lisa.RemoteCallResultProto.internal_static_RemoteCallResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              zh.lisa.RemoteCallResultProto.RemoteCallResult.class, zh.lisa.RemoteCallResultProto.RemoteCallResult.Builder.class);
    }

    public static com.google.protobuf.Parser<RemoteCallResult> PARSER =
        new com.google.protobuf.AbstractParser<RemoteCallResult>() {
      public RemoteCallResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RemoteCallResult(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RemoteCallResult> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required bool isSuccess = 1;
    public static final int ISSUCCESS_FIELD_NUMBER = 1;
    private boolean isSuccess_;
    /**
     * <code>required bool isSuccess = 1;</code>
     */
    public boolean hasIsSuccess() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bool isSuccess = 1;</code>
     */
    public boolean getIsSuccess() {
      return isSuccess_;
    }

    // optional bytes resultObj = 2;
    public static final int RESULTOBJ_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString resultObj_;
    /**
     * <code>optional bytes resultObj = 2;</code>
     */
    public boolean hasResultObj() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes resultObj = 2;</code>
     */
    public com.google.protobuf.ByteString getResultObj() {
      return resultObj_;
    }

    // optional string resultType = 3;
    public static final int RESULTTYPE_FIELD_NUMBER = 3;
    private java.lang.Object resultType_;
    /**
     * <code>optional string resultType = 3;</code>
     */
    public boolean hasResultType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string resultType = 3;</code>
     */
    public java.lang.String getResultType() {
      java.lang.Object ref = resultType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          resultType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string resultType = 3;</code>
     */
    public com.google.protobuf.ByteString
        getResultTypeBytes() {
      java.lang.Object ref = resultType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resultType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string errorMsg = 4;
    public static final int ERRORMSG_FIELD_NUMBER = 4;
    private java.lang.Object errorMsg_;
    /**
     * <code>optional string errorMsg = 4;</code>
     */
    public boolean hasErrorMsg() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string errorMsg = 4;</code>
     */
    public java.lang.String getErrorMsg() {
      java.lang.Object ref = errorMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errorMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string errorMsg = 4;</code>
     */
    public com.google.protobuf.ByteString
        getErrorMsgBytes() {
      java.lang.Object ref = errorMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 resultListSize = 5;
    public static final int RESULTLISTSIZE_FIELD_NUMBER = 5;
    private int resultListSize_;
    /**
     * <code>optional int32 resultListSize = 5;</code>
     */
    public boolean hasResultListSize() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 resultListSize = 5;</code>
     */
    public int getResultListSize() {
      return resultListSize_;
    }

    // optional string resultListType = 6;
    public static final int RESULTLISTTYPE_FIELD_NUMBER = 6;
    private java.lang.Object resultListType_;
    /**
     * <code>optional string resultListType = 6;</code>
     */
    public boolean hasResultListType() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string resultListType = 6;</code>
     */
    public java.lang.String getResultListType() {
      java.lang.Object ref = resultListType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          resultListType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string resultListType = 6;</code>
     */
    public com.google.protobuf.ByteString
        getResultListTypeBytes() {
      java.lang.Object ref = resultListType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resultListType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated int32 resultListObjLength = 7;
    public static final int RESULTLISTOBJLENGTH_FIELD_NUMBER = 7;
    private java.util.List<java.lang.Integer> resultListObjLength_;
    /**
     * <code>repeated int32 resultListObjLength = 7;</code>
     */
    public java.util.List<java.lang.Integer>
        getResultListObjLengthList() {
      return resultListObjLength_;
    }
    /**
     * <code>repeated int32 resultListObjLength = 7;</code>
     */
    public int getResultListObjLengthCount() {
      return resultListObjLength_.size();
    }
    /**
     * <code>repeated int32 resultListObjLength = 7;</code>
     */
    public int getResultListObjLength(int index) {
      return resultListObjLength_.get(index);
    }

    private void initFields() {
      isSuccess_ = false;
      resultObj_ = com.google.protobuf.ByteString.EMPTY;
      resultType_ = "";
      errorMsg_ = "";
      resultListSize_ = 0;
      resultListType_ = "";
      resultListObjLength_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasIsSuccess()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, isSuccess_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, resultObj_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getResultTypeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getErrorMsgBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, resultListSize_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getResultListTypeBytes());
      }
      for (int i = 0; i < resultListObjLength_.size(); i++) {
        output.writeInt32(7, resultListObjLength_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, isSuccess_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, resultObj_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getResultTypeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getErrorMsgBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, resultListSize_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getResultListTypeBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < resultListObjLength_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(resultListObjLength_.get(i));
        }
        size += dataSize;
        size += 1 * getResultListObjLengthList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static zh.lisa.RemoteCallResultProto.RemoteCallResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zh.lisa.RemoteCallResultProto.RemoteCallResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zh.lisa.RemoteCallResultProto.RemoteCallResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static zh.lisa.RemoteCallResultProto.RemoteCallResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static zh.lisa.RemoteCallResultProto.RemoteCallResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static zh.lisa.RemoteCallResultProto.RemoteCallResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static zh.lisa.RemoteCallResultProto.RemoteCallResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static zh.lisa.RemoteCallResultProto.RemoteCallResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static zh.lisa.RemoteCallResultProto.RemoteCallResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static zh.lisa.RemoteCallResultProto.RemoteCallResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(zh.lisa.RemoteCallResultProto.RemoteCallResult prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RemoteCallResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements zh.lisa.RemoteCallResultProto.RemoteCallResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return zh.lisa.RemoteCallResultProto.internal_static_RemoteCallResult_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return zh.lisa.RemoteCallResultProto.internal_static_RemoteCallResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                zh.lisa.RemoteCallResultProto.RemoteCallResult.class, zh.lisa.RemoteCallResultProto.RemoteCallResult.Builder.class);
      }

      // Construct using zh.lisa.RemoteCallResultProto.RemoteCallResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        isSuccess_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        resultObj_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        resultType_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        errorMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        resultListSize_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        resultListType_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        resultListObjLength_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return zh.lisa.RemoteCallResultProto.internal_static_RemoteCallResult_descriptor;
      }

      public zh.lisa.RemoteCallResultProto.RemoteCallResult getDefaultInstanceForType() {
        return zh.lisa.RemoteCallResultProto.RemoteCallResult.getDefaultInstance();
      }

      public zh.lisa.RemoteCallResultProto.RemoteCallResult build() {
        zh.lisa.RemoteCallResultProto.RemoteCallResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public zh.lisa.RemoteCallResultProto.RemoteCallResult buildPartial() {
        zh.lisa.RemoteCallResultProto.RemoteCallResult result = new zh.lisa.RemoteCallResultProto.RemoteCallResult(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.isSuccess_ = isSuccess_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.resultObj_ = resultObj_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.resultType_ = resultType_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.errorMsg_ = errorMsg_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.resultListSize_ = resultListSize_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.resultListType_ = resultListType_;
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          resultListObjLength_ = java.util.Collections.unmodifiableList(resultListObjLength_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.resultListObjLength_ = resultListObjLength_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof zh.lisa.RemoteCallResultProto.RemoteCallResult) {
          return mergeFrom((zh.lisa.RemoteCallResultProto.RemoteCallResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(zh.lisa.RemoteCallResultProto.RemoteCallResult other) {
        if (other == zh.lisa.RemoteCallResultProto.RemoteCallResult.getDefaultInstance()) return this;
        if (other.hasIsSuccess()) {
          setIsSuccess(other.getIsSuccess());
        }
        if (other.hasResultObj()) {
          setResultObj(other.getResultObj());
        }
        if (other.hasResultType()) {
          bitField0_ |= 0x00000004;
          resultType_ = other.resultType_;
          onChanged();
        }
        if (other.hasErrorMsg()) {
          bitField0_ |= 0x00000008;
          errorMsg_ = other.errorMsg_;
          onChanged();
        }
        if (other.hasResultListSize()) {
          setResultListSize(other.getResultListSize());
        }
        if (other.hasResultListType()) {
          bitField0_ |= 0x00000020;
          resultListType_ = other.resultListType_;
          onChanged();
        }
        if (!other.resultListObjLength_.isEmpty()) {
          if (resultListObjLength_.isEmpty()) {
            resultListObjLength_ = other.resultListObjLength_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureResultListObjLengthIsMutable();
            resultListObjLength_.addAll(other.resultListObjLength_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasIsSuccess()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        zh.lisa.RemoteCallResultProto.RemoteCallResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (zh.lisa.RemoteCallResultProto.RemoteCallResult) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bool isSuccess = 1;
      private boolean isSuccess_ ;
      /**
       * <code>required bool isSuccess = 1;</code>
       */
      public boolean hasIsSuccess() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bool isSuccess = 1;</code>
       */
      public boolean getIsSuccess() {
        return isSuccess_;
      }
      /**
       * <code>required bool isSuccess = 1;</code>
       */
      public Builder setIsSuccess(boolean value) {
        bitField0_ |= 0x00000001;
        isSuccess_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool isSuccess = 1;</code>
       */
      public Builder clearIsSuccess() {
        bitField0_ = (bitField0_ & ~0x00000001);
        isSuccess_ = false;
        onChanged();
        return this;
      }

      // optional bytes resultObj = 2;
      private com.google.protobuf.ByteString resultObj_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes resultObj = 2;</code>
       */
      public boolean hasResultObj() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes resultObj = 2;</code>
       */
      public com.google.protobuf.ByteString getResultObj() {
        return resultObj_;
      }
      /**
       * <code>optional bytes resultObj = 2;</code>
       */
      public Builder setResultObj(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        resultObj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes resultObj = 2;</code>
       */
      public Builder clearResultObj() {
        bitField0_ = (bitField0_ & ~0x00000002);
        resultObj_ = getDefaultInstance().getResultObj();
        onChanged();
        return this;
      }

      // optional string resultType = 3;
      private java.lang.Object resultType_ = "";
      /**
       * <code>optional string resultType = 3;</code>
       */
      public boolean hasResultType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string resultType = 3;</code>
       */
      public java.lang.String getResultType() {
        java.lang.Object ref = resultType_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          resultType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string resultType = 3;</code>
       */
      public com.google.protobuf.ByteString
          getResultTypeBytes() {
        java.lang.Object ref = resultType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resultType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string resultType = 3;</code>
       */
      public Builder setResultType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        resultType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string resultType = 3;</code>
       */
      public Builder clearResultType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        resultType_ = getDefaultInstance().getResultType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string resultType = 3;</code>
       */
      public Builder setResultTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        resultType_ = value;
        onChanged();
        return this;
      }

      // optional string errorMsg = 4;
      private java.lang.Object errorMsg_ = "";
      /**
       * <code>optional string errorMsg = 4;</code>
       */
      public boolean hasErrorMsg() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string errorMsg = 4;</code>
       */
      public java.lang.String getErrorMsg() {
        java.lang.Object ref = errorMsg_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          errorMsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string errorMsg = 4;</code>
       */
      public com.google.protobuf.ByteString
          getErrorMsgBytes() {
        java.lang.Object ref = errorMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string errorMsg = 4;</code>
       */
      public Builder setErrorMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        errorMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string errorMsg = 4;</code>
       */
      public Builder clearErrorMsg() {
        bitField0_ = (bitField0_ & ~0x00000008);
        errorMsg_ = getDefaultInstance().getErrorMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string errorMsg = 4;</code>
       */
      public Builder setErrorMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        errorMsg_ = value;
        onChanged();
        return this;
      }

      // optional int32 resultListSize = 5;
      private int resultListSize_ ;
      /**
       * <code>optional int32 resultListSize = 5;</code>
       */
      public boolean hasResultListSize() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 resultListSize = 5;</code>
       */
      public int getResultListSize() {
        return resultListSize_;
      }
      /**
       * <code>optional int32 resultListSize = 5;</code>
       */
      public Builder setResultListSize(int value) {
        bitField0_ |= 0x00000010;
        resultListSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 resultListSize = 5;</code>
       */
      public Builder clearResultListSize() {
        bitField0_ = (bitField0_ & ~0x00000010);
        resultListSize_ = 0;
        onChanged();
        return this;
      }

      // optional string resultListType = 6;
      private java.lang.Object resultListType_ = "";
      /**
       * <code>optional string resultListType = 6;</code>
       */
      public boolean hasResultListType() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string resultListType = 6;</code>
       */
      public java.lang.String getResultListType() {
        java.lang.Object ref = resultListType_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          resultListType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string resultListType = 6;</code>
       */
      public com.google.protobuf.ByteString
          getResultListTypeBytes() {
        java.lang.Object ref = resultListType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resultListType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string resultListType = 6;</code>
       */
      public Builder setResultListType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        resultListType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string resultListType = 6;</code>
       */
      public Builder clearResultListType() {
        bitField0_ = (bitField0_ & ~0x00000020);
        resultListType_ = getDefaultInstance().getResultListType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string resultListType = 6;</code>
       */
      public Builder setResultListTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        resultListType_ = value;
        onChanged();
        return this;
      }

      // repeated int32 resultListObjLength = 7;
      private java.util.List<java.lang.Integer> resultListObjLength_ = java.util.Collections.emptyList();
      private void ensureResultListObjLengthIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          resultListObjLength_ = new java.util.ArrayList<java.lang.Integer>(resultListObjLength_);
          bitField0_ |= 0x00000040;
         }
      }
      /**
       * <code>repeated int32 resultListObjLength = 7;</code>
       */
      public java.util.List<java.lang.Integer>
          getResultListObjLengthList() {
        return java.util.Collections.unmodifiableList(resultListObjLength_);
      }
      /**
       * <code>repeated int32 resultListObjLength = 7;</code>
       */
      public int getResultListObjLengthCount() {
        return resultListObjLength_.size();
      }
      /**
       * <code>repeated int32 resultListObjLength = 7;</code>
       */
      public int getResultListObjLength(int index) {
        return resultListObjLength_.get(index);
      }
      /**
       * <code>repeated int32 resultListObjLength = 7;</code>
       */
      public Builder setResultListObjLength(
          int index, int value) {
        ensureResultListObjLengthIsMutable();
        resultListObjLength_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 resultListObjLength = 7;</code>
       */
      public Builder addResultListObjLength(int value) {
        ensureResultListObjLengthIsMutable();
        resultListObjLength_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 resultListObjLength = 7;</code>
       */
      public Builder addAllResultListObjLength(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureResultListObjLengthIsMutable();
        super.addAll(values, resultListObjLength_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 resultListObjLength = 7;</code>
       */
      public Builder clearResultListObjLength() {
        resultListObjLength_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:RemoteCallResult)
    }

    static {
      defaultInstance = new RemoteCallResult(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RemoteCallResult)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RemoteCallResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RemoteCallResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026RemoteCallResult.proto\"\253\001\n\020RemoteCallR" +
      "esult\022\021\n\tisSuccess\030\001 \002(\010\022\021\n\tresultObj\030\002 " +
      "\001(\014\022\022\n\nresultType\030\003 \001(\t\022\020\n\010errorMsg\030\004 \001(" +
      "\t\022\026\n\016resultListSize\030\005 \001(\005\022\026\n\016resultListT" +
      "ype\030\006 \001(\t\022\033\n\023resultListObjLength\030\007 \003(\005B " +
      "\n\007zh.lisaB\025RemoteCallResultProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_RemoteCallResult_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_RemoteCallResult_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_RemoteCallResult_descriptor,
              new java.lang.String[] { "IsSuccess", "ResultObj", "ResultType", "ErrorMsg", "ResultListSize", "ResultListType", "ResultListObjLength", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
